DROP TABLE IF EXISTS languages;

CREATE TABLE languages (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(250) NOT NULL,
    audio BINARY LARGE OBJECT NOT NULL,
    script BINARY LARGE OBJECT NOT NULL
);